/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#0e1416",
        surface: "#0e1416",
        "surface-dim": "#0e1416",
        "surface-bright": "#343a3c",
        "surface-container-lowest": "#090f11",
        "surface-container-low": "#171d1e",
        "surface-container": "#1b2122",
        "surface-container-high": "#252b2d",
        "surface-container-highest": "#303638",
        "on-surface": "#dee3e6",
        "on-surface-variant": "#bcc9cd",
        "inverse-surface": "#dee3e6",
        "inverse-on-surface": "#2b3133",
        outline: "#869397",
        "outline-variant": "#3d494c",
        "surface-tint": "#4cd7f6",
        primary: "#06b6d4",
        "primary-bright": "#4cd7f6",
        "on-primary": "#003640",
        "primary-container": "#06b6d4",
        "on-primary-container": "#00424f",
        "inverse-primary": "#00687a",
        secondary: "#d0bcff",
        "on-secondary": "#3c0091",
        "secondary-container": "#571bc1",
        "on-secondary-container": "#c4abff",
        tertiary: "#ffb873",
        "on-tertiary": "#4b2800",
        "tertiary-container": "#e89337",
        "on-tertiary-container": "#5b3200",
        error: "#ffb4ab",
        "error-bright": "#ef4444",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#acedff",
        "primary-fixed-dim": "#4cd7f6",
        "on-primary-fixed": "#001f26",
        "on-primary-fixed-variant": "#004e5c",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#5516be",
        "tertiary-fixed": "#ffdcbf",
        "tertiary-fixed-dim": "#ffb873",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#6a3b00",
        "on-background": "#dee3e6",
        "surface-variant": "#303638"
      },
      fontFamily: {
        sans: ["Geist", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        geist: ["Geist", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      boxShadow: {
        'glow-cyan': '0 0 15px rgba(6, 182, 212, 0.3)',
        'glow-red': '0 0 15px rgba(239, 68, 68, 0.3)',
        'glow-amber': '0 0 15px rgba(245, 158, 11, 0.3)',
      }
    },
  },
  plugins: [],
}
